### ISSUE TITLE
Text Formatting Error!

### ISSUE THREAD

**Issue by ravibalg-aj** [Legolas10/Customer-SpendingScore-Segmentation#1]
In your kmeansclust.py file on line 32 you've spaced wrongly in the middle.
It should be "IS OPTIMUM" but you've spelled "I SOPTIMUM"!
I think so!
My First Issue😍

**Comment by paveethrans** [comment]
YESSS...THANK YOU SO MUCH...I have corrected it and removing that error gave me a better output accuracy !!!! 😁
My First Issue reply !!😍

**Comment by paveethrans** [comment]
🤣🤣🤣🤣
